packages:
  - 'packages/**'
  - 'tooling/**'
  - '!packages/**/.temp/**'

catalogs:
  dev:
    '@pixpilot/dev-config': ^3.16.0
    '@types/node': ^22.18.11
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    eslint: ^9.38.0
    glob: ^11.0.3
    prettier: ^3.6.2
    tsdown: ^0.15.11
    typescript: ^5.9.3
    vitest: ^3.2.4
